#!/usr/bin/env python3
"""
Optimized Blender Script Generator for MOCAP Conversion

This module generates efficient Blender scripts from CSV mocap data that avoid
performance issues and crashes by using batch keyframe insertion and memory optimization.
"""

import csv
import json
import os
import math
from typing import Dict, List, Tuple, Any, Optional
from DIZIONARIO import BONE_MAP_UNIFICATA


class BlenderScriptGenerator:
    """
    Generates optimized Blender scripts from mocap CSV data.
    
    Features:
    - Batch keyframe insertion instead of individual calls
    - Progress feedback during execution
    - Memory optimization with chunk processing
    - Error handling with try/catch blocks
    - Frame sampling for testing
    - JSON export alternative
    """
    
    def __init__(self, csv_file: str, bone_mapping: Optional[Dict] = None):
        """
        Initialize the generator.
        
        Args:
            csv_file: Path to the CSV mocap data file
            bone_mapping: Optional custom bone mapping, defaults to BONE_MAP_UNIFICATA
        """
        self.csv_file = csv_file
        self.bone_mapping = bone_mapping or BONE_MAP_UNIFICATA
        self.data = []
        self.headers = []
        self.frame_count = 0
        
    def load_csv_data(self) -> None:
        """Load and parse CSV mocap data."""
        print("Loading CSV data...")
        try:
            with open(self.csv_file, 'r', encoding='utf-8') as file:
                reader = csv.DictReader(file)
                self.headers = reader.fieldnames
                self.data = list(reader)
                self.frame_count = len(self.data)
            print(f"Loaded {self.frame_count} frames with {len(self.headers)} channels")
        except Exception as e:
            raise Exception(f"Failed to load CSV data: {str(e)}")
    
    def _get_bone_info(self, blendshape_name: str) -> Optional[Dict]:
        """
        Get bone information for a given blendshape name.
        
        Args:
            blendshape_name: Name of the blendshape to map
            
        Returns:
            Dictionary with bone, object, and transform_type or None if not found
        """
        # Try exact match first
        if blendshape_name in self.bone_mapping:
            return self.bone_mapping[blendshape_name]
        
        # Convert PascalCase to camelCase (EyeBlinkLeft -> eyeBlinkLeft)
        camel_case_name = blendshape_name[0].lower() + blendshape_name[1:] if blendshape_name else ""
        if camel_case_name in self.bone_mapping:
            return self.bone_mapping[camel_case_name]
        
        # Try with different suffixes for different sources
        for name_variant in [blendshape_name, camel_case_name]:
            for suffix in ['_face_cap', '_epic', '_a2f', '']:
                key = f"{name_variant}{suffix}"
                if key in self.bone_mapping:
                    return self.bone_mapping[key]
                
        return None
    
    def generate_optimized_script(self, 
                                output_file: str = "mocap_animation.py",
                                chunk_size: int = 50,
                                frame_step: int = 1,
                                start_frame: int = 1) -> str:
        """
        Generate an optimized Blender script with batch keyframe insertion.
        
        Args:
            output_file: Output script filename
            chunk_size: Number of frames to process in each chunk
            frame_step: Frame sampling step (1 = every frame, 2 = every other frame, etc.)
            start_frame: Starting frame number in Blender
            
        Returns:
            Path to the generated script file
        """
        if not self.data:
            self.load_csv_data()
        
        print(f"Generating optimized Blender script...")
        print(f"Processing {self.frame_count} frames with step {frame_step} in chunks of {chunk_size}")
        
        script_content = self._generate_script_header()
        script_content += self._generate_batch_keyframe_code(chunk_size, frame_step, start_frame)
        script_content += self._generate_script_footer()
        
        with open(output_file, 'w', encoding='utf-8') as file:
            file.write(script_content)
        
        print(f"Generated optimized script: {output_file}")
        return output_file
    
    def _generate_script_header(self) -> str:
        """Generate the header portion of the Blender script."""
        return '''import bpy
import bmesh
import mathutils
from mathutils import Vector
import time

# Animation Import Script - Optimized for Performance
# Generated by BlenderScriptGenerator
print("Starting mocap animation import...")

def safe_keyframe_insert(obj, data_path, frame, value, group_name=""):
    """Safely insert a keyframe with error handling."""
    try:
        if hasattr(obj, data_path.split('.')[0]):
            obj.keyframe_insert(data_path=data_path, frame=frame, group=group_name)
            return True
    except Exception as e:
        print(f"Warning: Failed to insert keyframe for {data_path} at frame {frame}: {e}")
        return False
    return False

def batch_keyframe_insert(keyframe_data, progress_callback=None):
    """
    Insert keyframes in batches for better performance.
    
    Args:
        keyframe_data: List of (object, data_path, frame, value, group) tuples
        progress_callback: Optional callback for progress updates
    """
    total_keyframes = len(keyframe_data)
    print(f"Inserting {total_keyframes} keyframes in batches...")
    
    # Group keyframes by object and data path for efficiency
    grouped_keyframes = {}
    for obj_name, data_path, frame, value, group in keyframe_data:
        key = (obj_name, data_path)
        if key not in grouped_keyframes:
            grouped_keyframes[key] = []
        grouped_keyframes[key].append((frame, value, group))
    
    success_count = 0
    total_groups = len(grouped_keyframes)
    
    for i, ((obj_name, data_path), keyframes) in enumerate(grouped_keyframes.items()):
        try:
            # Get the object
            obj = bpy.data.objects.get(obj_name)
            if not obj:
                print(f"Warning: Object '{obj_name}' not found")
                continue
            
            # Select and make active
            bpy.context.view_layer.objects.active = obj
            obj.select_set(True)
            
            # Insert keyframes for this object/data_path combination
            for frame, value, group in keyframes:
                # Set the value
                try:
                    if '.' in data_path:
                        # Handle nested attributes (e.g., pose.bones["name"].location)
                        parts = data_path.split('.')
                        current_obj = obj
                        for part in parts[:-1]:
                            if '[' in part and ']' in part:
                                # Handle array access like bones["name"]
                                attr_name = part.split('[')[0]
                                index_part = part.split('[')[1].split(']')[0]
                                index = index_part.replace('"', '').replace("'", '')
                                current_obj = getattr(current_obj, attr_name)[index]
                            else:
                                current_obj = getattr(current_obj, part)
                        
                        # Set the final value
                        final_attr = parts[-1]
                        if hasattr(current_obj, final_attr):
                            if isinstance(getattr(current_obj, final_attr), (int, float)):
                                setattr(current_obj, final_attr, float(value))
                            else:
                                # Handle vector/array types
                                current_value = getattr(current_obj, final_attr)
                                if hasattr(current_value, '__setitem__'):
                                    # This is likely a vector or array
                                    if len(current_value) > 0:
                                        current_value[0] = float(value)  # Assuming single axis for now
                    else:
                        # Simple attribute
                        if hasattr(obj, data_path):
                            setattr(obj, data_path, float(value))
                    
                    # Insert keyframe
                    if safe_keyframe_insert(obj, data_path, frame, value, group):
                        success_count += 1
                        
                except Exception as e:
                    print(f"Error setting value for {obj_name}.{data_path} at frame {frame}: {e}")
                    continue
            
            # Update progress
            if progress_callback:
                progress = (i + 1) / total_groups * 100
                progress_callback(progress, f"Processing {obj_name}.{data_path}")
            elif i % 10 == 0:  # Print progress every 10 groups
                progress = (i + 1) / total_groups * 100
                print(f"Progress: {progress:.1f}% ({i+1}/{total_groups} bone mappings)")
                
        except Exception as e:
            print(f"Error processing {obj_name}.{data_path}: {e}")
            continue
    
    print(f"Successfully inserted {success_count} keyframes")
    return success_count

# Start timing
start_time = time.time()

'''

    def _generate_batch_keyframe_code(self, chunk_size: int, frame_step: int, start_frame: int) -> str:
        """Generate the main keyframe insertion code with batching."""
        code = "# Prepare keyframe data\nkeyframe_data = []\n\n"
        
        # Process data in chunks
        for chunk_start in range(0, len(self.data), chunk_size):
            chunk_end = min(chunk_start + chunk_size, len(self.data))
            code += f"# Processing frames {chunk_start + 1} to {chunk_end}\n"
            code += "chunk_keyframes = []\n"
            
            for i in range(chunk_start, chunk_end, frame_step):
                frame_data = self.data[i]
                blender_frame = start_frame + i
                
                # Process each blendshape in the frame
                for header in self.headers:
                    if header in ['Timecode', 'BlendShapeCount']:
                        continue
                        
                    bone_info = self._get_bone_info(header)
                    if not bone_info or not bone_info.get('bone'):
                        continue
                    
                    try:
                        value = float(frame_data[header])
                        if abs(value) < 0.0001:  # Skip near-zero values for performance
                            continue
                            
                        # Generate data path based on transform type
                        obj_name = bone_info['object']
                        bone_name = bone_info['bone']
                        transform_type = bone_info['transform_type']
                        
                        data_path = self._get_data_path(bone_name, transform_type)
                        group_name = f"{bone_name}_{transform_type}"
                        
                        # Escape quotes in data_path for safe code generation
                        escaped_data_path = data_path.replace('"', '\\"')
                        code += f'chunk_keyframes.append(("{obj_name}", "{escaped_data_path}", {blender_frame}, {value}, "{group_name}"))\n'
                        
                    except (ValueError, KeyError) as e:
                        continue
            
            code += "keyframe_data.extend(chunk_keyframes)\n"
            code += f'print("Prepared chunk {chunk_start // chunk_size + 1}: {{}} keyframes".format(len(chunk_keyframes)))\n\n'
        
        code += '''
# Insert all keyframes in batches
print(f"Total keyframes prepared: {len(keyframe_data)}")
if keyframe_data:
    batch_keyframe_insert(keyframe_data)
else:
    print("No keyframes to insert")

'''
        return code
    
    def _get_data_path(self, bone_name: str, transform_type: str) -> str:
        """
        Generate the appropriate Blender data path for a bone and transform type.
        
        Args:
            bone_name: Name of the bone
            transform_type: Type of transformation (LOC_X, LOC_Y, LOC_Z, ROT_X, ROT_Y, ROT_Z)
            
        Returns:
            Blender data path string
        """
        if transform_type.startswith('LOC_'):
            axis = transform_type.split('_')[1].lower()
            axis_index = {'x': 0, 'y': 1, 'z': 2}[axis]
            return f'pose.bones["{bone_name}"].location[{axis_index}]'
        elif transform_type.startswith('ROT_'):
            axis = transform_type.split('_')[1].lower()
            axis_index = {'x': 0, 'y': 1, 'z': 2}[axis]
            return f'pose.bones["{bone_name}"].rotation_euler[{axis_index}]'
        else:
            # Default to location X if unknown
            return f'pose.bones["{bone_name}"].location[0]'
    
    def _generate_script_footer(self) -> str:
        """Generate the footer portion of the Blender script."""
        return '''
# Finalize
end_time = time.time()
print(f"Animation import completed in {end_time - start_time:.2f} seconds")

# Update scene
bpy.context.scene.frame_end = max([kf[2] for kf in keyframe_data]) if keyframe_data else 1
print(f"Scene frame range updated to: 1 - {bpy.context.scene.frame_end}")

print("Mocap animation import finished successfully!")
'''

    def export_to_json(self, output_file: str = "mocap_data.json", frame_step: int = 1) -> str:
        """
        Export mocap data to JSON format for lightweight import.
        
        Args:
            output_file: Output JSON filename
            frame_step: Frame sampling step
            
        Returns:
            Path to the generated JSON file
        """
        if not self.data:
            self.load_csv_data()
        
        print(f"Exporting to JSON format with frame step {frame_step}...")
        
        json_data = {
            "metadata": {
                "total_frames": self.frame_count,
                "frame_step": frame_step,
                "exported_frames": len(range(0, self.frame_count, frame_step)),
                "bone_mapping": self.bone_mapping
            },
            "animation_data": []
        }
        
        for i in range(0, len(self.data), frame_step):
            frame_data = self.data[i]
            frame_info = {
                "frame": i + 1,
                "timecode": frame_data.get('Timecode', ''),
                "blendshapes": {}
            }
            
            for header in self.headers:
                if header in ['Timecode', 'BlendShapeCount']:
                    continue
                
                try:
                    value = float(frame_data[header])
                    if abs(value) > 0.0001:  # Only include non-zero values
                        bone_info = self._get_bone_info(header)
                        if bone_info and bone_info.get('bone'):
                            frame_info["blendshapes"][header] = {
                                "value": value,
                                "bone": bone_info['bone'],
                                "object": bone_info['object'],
                                "transform_type": bone_info['transform_type']
                            }
                except (ValueError, KeyError):
                    continue
            
            if frame_info["blendshapes"]:  # Only add frames with data
                json_data["animation_data"].append(frame_info)
        
        with open(output_file, 'w', encoding='utf-8') as file:
            json.dump(json_data, file, indent=2)
        
        print(f"Exported {len(json_data['animation_data'])} frames to {output_file}")
        return output_file

    def generate_json_importer_script(self, 
                                    json_file: str = "mocap_data.json",
                                    output_file: str = "json_importer.py") -> str:
        """
        Generate a lightweight Blender script that imports from JSON.
        
        Args:
            json_file: JSON data file to import
            output_file: Output script filename
            
        Returns:
            Path to the generated script file
        """
        script_content = f'''import bpy
import json
import time

print("Starting JSON-based mocap import...")

def import_from_json(json_file_path):
    """Import animation data from JSON file."""
    start_time = time.time()
    
    try:
        with open(json_file_path, 'r', encoding='utf-8') as file:
            data = json.load(file)
        
        print(f"Loaded JSON data: {{data['metadata']['exported_frames']}} frames")
        
        keyframes_inserted = 0
        total_frames = len(data['animation_data'])
        
        for i, frame_data in enumerate(data['animation_data']):
            frame_num = frame_data['frame']
            
            for blendshape_name, blendshape_data in frame_data['blendshapes'].items():
                try:
                    obj_name = blendshape_data['object']
                    bone_name = blendshape_data['bone']
                    transform_type = blendshape_data['transform_type']
                    value = blendshape_data['value']
                    
                    # Get object
                    obj = bpy.data.objects.get(obj_name)
                    if not obj:
                        continue
                    
                    # Set object as active
                    bpy.context.view_layer.objects.active = obj
                    
                    # Set value and insert keyframe
                    if transform_type.startswith('LOC_'):
                        axis = transform_type.split('_')[1].lower()
                        axis_index = {{'x': 0, 'y': 1, 'z': 2}}[axis]
                        obj.pose.bones[bone_name].location[axis_index] = value
                        data_path = f'pose.bones["{{bone_name}}"].location'
                        obj.keyframe_insert(data_path=data_path, index=axis_index, frame=frame_num)
                    elif transform_type.startswith('ROT_'):
                        axis = transform_type.split('_')[1].lower()
                        axis_index = {{'x': 0, 'y': 1, 'z': 2}}[axis]
                        obj.pose.bones[bone_name].rotation_euler[axis_index] = value
                        data_path = f'pose.bones["{{bone_name}}"].rotation_euler'
                        obj.keyframe_insert(data_path=data_path, index=axis_index, frame=frame_num)
                    
                    keyframes_inserted += 1
                    
                except Exception as e:
                    print(f"Error processing {{blendshape_name}}: {{e}}")
                    continue
            
            # Progress update
            if i % 50 == 0:
                progress = (i + 1) / total_frames * 100
                print(f"Progress: {{progress:.1f}}% ({{i+1}}/{{total_frames}} frames)")
        
        print(f"Import completed: {{keyframes_inserted}} keyframes in {{time.time() - start_time:.2f}} seconds")
        
        # Update scene frame range
        if data['animation_data']:
            max_frame = max(frame['frame'] for frame in data['animation_data'])
            bpy.context.scene.frame_end = max_frame
            print(f"Scene frame range updated to: 1 - {{max_frame}}")
        
    except Exception as e:
        print(f"Error importing JSON data: {{e}}")
        raise

# Import the data
import_from_json("{json_file}")
print("JSON import completed!")
'''

        with open(output_file, 'w', encoding='utf-8') as file:
            file.write(script_content)
        
        print(f"Generated JSON importer script: {output_file}")
        return output_file


def main():
    """Main function for command-line usage."""
    import argparse
    
    parser = argparse.ArgumentParser(description='Generate optimized Blender scripts from mocap CSV data')
    parser.add_argument('csv_file', help='Path to CSV mocap data file')
    parser.add_argument('--output', '-o', default='mocap_animation.py', 
                       help='Output script filename (default: mocap_animation.py)')
    parser.add_argument('--chunk-size', '-c', type=int, default=50,
                       help='Chunk size for processing (default: 50)')
    parser.add_argument('--frame-step', '-s', type=int, default=1,
                       help='Frame sampling step (default: 1)')
    parser.add_argument('--start-frame', '-f', type=int, default=1,
                       help='Starting frame in Blender (default: 1)')
    parser.add_argument('--json', action='store_true',
                       help='Also export to JSON format')
    parser.add_argument('--json-only', action='store_true',
                       help='Only export to JSON format (no Python script)')
    
    args = parser.parse_args()
    
    if not os.path.exists(args.csv_file):
        print(f"Error: CSV file '{args.csv_file}' not found")
        return 1
    
    try:
        generator = BlenderScriptGenerator(args.csv_file)
        
        if args.json_only:
            json_file = generator.export_to_json(frame_step=args.frame_step)
            generator.generate_json_importer_script(json_file)
        else:
            script_file = generator.generate_optimized_script(
                output_file=args.output,
                chunk_size=args.chunk_size,
                frame_step=args.frame_step,
                start_frame=args.start_frame
            )
            
            if args.json:
                json_file = generator.export_to_json(frame_step=args.frame_step)
                generator.generate_json_importer_script(json_file)
        
        print("Generation completed successfully!")
        return 0
        
    except Exception as e:
        print(f"Error: {e}")
        return 1


if __name__ == "__main__":
    exit(main())