import bpy
import bmesh
import mathutils
from mathutils import Vector
import time

# Animation Import Script - Optimized for Performance
# Generated by BlenderScriptGenerator
print("Starting mocap animation import...")

def safe_keyframe_insert(obj, data_path, frame, value, group_name=""):
    """Safely insert a keyframe with error handling."""
    try:
        if hasattr(obj, data_path.split('.')[0]):
            obj.keyframe_insert(data_path=data_path, frame=frame, group=group_name)
            return True
    except Exception as e:
        print(f"Warning: Failed to insert keyframe for {data_path} at frame {frame}: {e}")
        return False
    return False

def batch_keyframe_insert(keyframe_data, progress_callback=None):
    """
    Insert keyframes in batches for better performance.
    
    Args:
        keyframe_data: List of (object, data_path, frame, value, group) tuples
        progress_callback: Optional callback for progress updates
    """
    total_keyframes = len(keyframe_data)
    print(f"Inserting {total_keyframes} keyframes in batches...")
    
    # Group keyframes by object and data path for efficiency
    grouped_keyframes = {}
    for obj_name, data_path, frame, value, group in keyframe_data:
        key = (obj_name, data_path)
        if key not in grouped_keyframes:
            grouped_keyframes[key] = []
        grouped_keyframes[key].append((frame, value, group))
    
    success_count = 0
    total_groups = len(grouped_keyframes)
    
    for i, ((obj_name, data_path), keyframes) in enumerate(grouped_keyframes.items()):
        try:
            # Get the object
            obj = bpy.data.objects.get(obj_name)
            if not obj:
                print(f"Warning: Object '{obj_name}' not found")
                continue
            
            # Select and make active
            bpy.context.view_layer.objects.active = obj
            obj.select_set(True)
            
            # Insert keyframes for this object/data_path combination
            for frame, value, group in keyframes:
                # Set the value
                try:
                    if '.' in data_path:
                        # Handle nested attributes (e.g., pose.bones["name"].location)
                        parts = data_path.split('.')
                        current_obj = obj
                        for part in parts[:-1]:
                            if '[' in part and ']' in part:
                                # Handle array access like bones["name"]
                                attr_name = part.split('[')[0]
                                index_part = part.split('[')[1].split(']')[0]
                                index = index_part.replace('"', '').replace("'", '')
                                current_obj = getattr(current_obj, attr_name)[index]
                            else:
                                current_obj = getattr(current_obj, part)
                        
                        # Set the final value
                        final_attr = parts[-1]
                        if hasattr(current_obj, final_attr):
                            if isinstance(getattr(current_obj, final_attr), (int, float)):
                                setattr(current_obj, final_attr, float(value))
                            else:
                                # Handle vector/array types
                                current_value = getattr(current_obj, final_attr)
                                if hasattr(current_value, '__setitem__'):
                                    # This is likely a vector or array
                                    if len(current_value) > 0:
                                        current_value[0] = float(value)  # Assuming single axis for now
                    else:
                        # Simple attribute
                        if hasattr(obj, data_path):
                            setattr(obj, data_path, float(value))
                    
                    # Insert keyframe
                    if safe_keyframe_insert(obj, data_path, frame, value, group):
                        success_count += 1
                        
                except Exception as e:
                    print(f"Error setting value for {obj_name}.{data_path} at frame {frame}: {e}")
                    continue
            
            # Update progress
            if progress_callback:
                progress = (i + 1) / total_groups * 100
                progress_callback(progress, f"Processing {obj_name}.{data_path}")
            elif i % 10 == 0:  # Print progress every 10 groups
                progress = (i + 1) / total_groups * 100
                print(f"Progress: {progress:.1f}% ({i+1}/{total_groups} bone mappings)")
                
        except Exception as e:
            print(f"Error processing {obj_name}.{data_path}: {e}")
            continue
    
    print(f"Successfully inserted {success_count} keyframes")
    return success_count

# Start timing
start_time = time.time()

# Prepare keyframe data
keyframe_data = []

# Processing frames 1 to 50
chunk_keyframes = []
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 1, 0.1173306, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 1, 0.18357788, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 1, 0.20758107, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 1, 0.02790979, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 1, 0.04860202, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.L\"].location[1]", 1, 0.34338242, "c_eyelid_lower.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 1, 0.00521958, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 1, 0.06477024, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 1, 0.16739362, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 1, 0.01164191, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 1, 0.22884054, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 1, 0.05752239, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.R\"].location[1]", 1, 0.33392572, "c_eyelid_lower.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 1, 0.00784608, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[2]", 1, 0.0001275, "c_jaw_target_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 1, 0.00246498, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[1]", 1, 0.01473731, "c_jaw_target_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_close\"].location[2]", 1, 0.00087887, "c_mouth_close_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_funnel\"].location[2]", 1, 0.00046822, "c_mouth_funnel_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_pucker\"].location[2]", 1, 0.00395376, "c_mouth_pucker_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.L\"].rotation_euler[2]", 1, 0.00036647, "c_mouth_smile.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.R\"].rotation_euler[2]", 1, 0.0002458, "c_mouth_smile.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.L\"].rotation_euler[2]", 1, 0.0003857, "c_mouth_frown.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.R\"].rotation_euler[2]", 1, 0.00051114, "c_mouth_frown.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 26, 0.17769915, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 26, 0.15077727, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 26, 0.09147372, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 26, 0.06219152, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 26, 0.06506431, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.L\"].location[1]", 26, 0.37085685, "c_eyelid_lower.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 26, 0.00382003, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 26, 0.09455176, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 26, 0.14251789, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 26, 0.02457592, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 26, 0.16074383, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 26, 0.0714704, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.R\"].location[1]", 26, 0.35762966, "c_eyelid_lower.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 26, 0.00485392, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[2]", 26, 0.00012938, "c_jaw_target_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 26, 0.00293515, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[1]", 26, 0.00891822, "c_jaw_target_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_close\"].location[2]", 26, 0.00081237, "c_mouth_close_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_funnel\"].location[2]", 26, 0.0003406, "c_mouth_funnel_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_pucker\"].location[2]", 26, 0.00411515, "c_mouth_pucker_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.L\"].rotation_euler[2]", 26, 0.00047881, "c_mouth_smile.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.R\"].rotation_euler[2]", 26, 0.00027336, "c_mouth_smile.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.L\"].rotation_euler[2]", 26, 0.00061529, "c_mouth_frown.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.R\"].rotation_euler[2]", 26, 0.00088358, "c_mouth_frown.R_ROT_Z"))
keyframe_data.extend(chunk_keyframes)
print("Prepared chunk 1: {} keyframes".format(len(chunk_keyframes)))

# Processing frames 51 to 100
chunk_keyframes = []
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 51, 0.13341114, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 51, 0.15671057, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 51, 0.03250477, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 51, 0.13274702, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 51, 0.05773252, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.L\"].location[1]", 51, 0.32702023, "c_eyelid_lower.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 51, 0.00597722, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 51, 0.0577823, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 51, 0.1491368, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 51, 0.05063425, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 51, 0.0966953, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 51, 0.06398761, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.R\"].location[1]", 51, 0.26945916, "c_eyelid_lower.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 51, 0.00818226, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[2]", 51, 0.00014532, "c_jaw_target_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 51, 0.00207727, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[1]", 51, 0.01080953, "c_jaw_target_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_close\"].location[2]", 51, 0.00086371, "c_mouth_close_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_funnel\"].location[2]", 51, 0.00034447, "c_mouth_funnel_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_pucker\"].location[2]", 51, 0.00457881, "c_mouth_pucker_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.L\"].rotation_euler[2]", 51, 0.00029666, "c_mouth_smile.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.R\"].rotation_euler[2]", 51, 0.00016808, "c_mouth_smile.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.L\"].rotation_euler[2]", 51, 0.00094736, "c_mouth_frown.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.R\"].rotation_euler[2]", 51, 0.0014366, "c_mouth_frown.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 76, 0.09424378, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 76, 0.12055055, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 76, 0.03050322, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 76, 0.13654496, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 76, 0.07098471, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.L\"].location[1]", 76, 0.30401325, "c_eyelid_lower.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 76, 0.00822837, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 76, 0.03404283, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 76, 0.11350025, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 76, 0.05129992, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 76, 0.09622476, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 76, 0.08467367, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.R\"].location[1]", 76, 0.21114728, "c_eyelid_lower.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 76, 0.01334253, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 76, 0.00210105, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[1]", 76, 0.00958912, "c_jaw_target_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_close\"].location[2]", 76, 0.00068362, "c_mouth_close_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_funnel\"].location[2]", 76, 0.00034057, "c_mouth_funnel_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_pucker\"].location[2]", 76, 0.01083621, "c_mouth_pucker_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.L\"].rotation_euler[2]", 76, 0.00010852, "c_mouth_smile.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.L\"].rotation_euler[2]", 76, 0.00079549, "c_mouth_frown.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.R\"].rotation_euler[2]", 76, 0.00113564, "c_mouth_frown.R_ROT_Z"))
keyframe_data.extend(chunk_keyframes)
print("Prepared chunk 2: {} keyframes".format(len(chunk_keyframes)))

# Processing frames 101 to 150
chunk_keyframes = []
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 101, 0.09601054, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 101, 0.0984168, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 101, 0.15371393, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 101, 0.03591713, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 101, 0.09609891, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.L\"].location[1]", 101, 0.33393586, "c_eyelid_lower.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 101, 0.00804043, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 101, 0.03642641, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 101, 0.09208748, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 101, 0.01878528, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 101, 0.17539376, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 101, 0.11214609, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.R\"].location[1]", 101, 0.2107881, "c_eyelid_lower.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 101, 0.01257551, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 101, 0.00227173, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[1]", 101, 0.009757, "c_jaw_target_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_close\"].location[2]", 101, 0.00079893, "c_mouth_close_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_funnel\"].location[2]", 101, 0.00038266, "c_mouth_funnel_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_pucker\"].location[2]", 101, 0.00904825, "c_mouth_pucker_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.L\"].rotation_euler[2]", 101, 0.00013454, "c_mouth_smile.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.L\"].rotation_euler[2]", 101, 0.00059985, "c_mouth_frown.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.R\"].rotation_euler[2]", 101, 0.00112797, "c_mouth_frown.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 126, 0.08338443, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 126, 0.1383435, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 126, 0.41249764, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 126, 0.01355284, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 126, 0.0647656, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.L\"].location[1]", 126, 0.29006743, "c_eyelid_lower.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 126, 0.00835137, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 126, 0.02433812, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 126, 0.11770704, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 126, 0.00413673, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 126, 0.38022411, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 126, 0.08114052, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.R\"].location[1]", 126, 0.16624904, "c_eyelid_lower.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 126, 0.019697, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[2]", 126, 0.00010314, "c_jaw_target_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 126, 0.00363506, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[1]", 126, 0.01253121, "c_jaw_target_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_close\"].location[2]", 126, 0.00104901, "c_mouth_close_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_funnel\"].location[2]", 126, 0.00045207, "c_mouth_funnel_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_pucker\"].location[2]", 126, 0.00677683, "c_mouth_pucker_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.L\"].rotation_euler[2]", 126, 0.00019153, "c_mouth_smile.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.R\"].rotation_euler[2]", 126, 0.00013541, "c_mouth_smile.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.L\"].rotation_euler[2]", 126, 0.0006889, "c_mouth_frown.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.R\"].rotation_euler[2]", 126, 0.00121509, "c_mouth_frown.R_ROT_Z"))
keyframe_data.extend(chunk_keyframes)
print("Prepared chunk 3: {} keyframes".format(len(chunk_keyframes)))

# Processing frames 151 to 200
chunk_keyframes = []
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 151, 0.09512791, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 151, 0.09864005, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 151, 0.0770466, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 151, 0.06401817, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 151, 0.08660775, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.L\"].location[1]", 151, 0.30032521, "c_eyelid_lower.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 151, 0.00803785, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 151, 0.04630291, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 151, 0.09888109, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 151, 0.03836761, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 151, 0.11578699, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 151, 0.09500144, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.R\"].location[1]", 151, 0.20625803, "c_eyelid_lower.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 151, 0.00948152, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[2]", 151, 0.00030429, "c_jaw_target_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 151, 0.00127983, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[1]", 151, 0.00269457, "c_jaw_target_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_close\"].location[2]", 151, 0.00028767, "c_mouth_close_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_funnel\"].location[2]", 151, 0.00030182, "c_mouth_funnel_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_pucker\"].location[2]", 151, 0.00056283, "c_mouth_pucker_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.L\"].rotation_euler[2]", 151, 0.02633386, "c_mouth_smile.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.R\"].rotation_euler[2]", 151, 0.01750213, "c_mouth_smile.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.L\"].rotation_euler[2]", 151, 0.00031639, "c_mouth_frown.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.R\"].rotation_euler[2]", 151, 0.00040485, "c_mouth_frown.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 176, 0.14297433, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 176, 0.19475316, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 176, 0.07363993, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 176, 0.05980763, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 176, 0.04591058, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.L\"].location[1]", 176, 0.3794795, "c_eyelid_lower.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 176, 0.0068394, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 176, 0.08715486, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 176, 0.19797114, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 176, 0.03883822, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 176, 0.10349822, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 176, 0.04309598, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.R\"].location[1]", 176, 0.27093154, "c_eyelid_lower.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 176, 0.00616413, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[2]", 176, 0.00021583, "c_jaw_target_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 176, 0.00075233, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[1]", 176, 0.00120955, "c_jaw_target_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_funnel\"].location[2]", 176, 0.00028573, "c_mouth_funnel_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_pucker\"].location[2]", 176, 0.00126506, "c_mouth_pucker_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.L\"].rotation_euler[2]", 176, 0.67702186, "c_mouth_smile.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.R\"].rotation_euler[2]", 176, 0.56531262, "c_mouth_smile.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.L\"].rotation_euler[2]", 176, 0.00091426, "c_mouth_frown.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.R\"].rotation_euler[2]", 176, 0.0009418, "c_mouth_frown.R_ROT_Z"))
keyframe_data.extend(chunk_keyframes)
print("Prepared chunk 4: {} keyframes".format(len(chunk_keyframes)))

# Processing frames 201 to 250
chunk_keyframes = []
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 201, 0.5862301, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 201, 0.54950207, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 201, 0.07456706, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 201, 0.07714885, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 201, 0.01046647, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.L\"].location[1]", 201, 0.56207073, "c_eyelid_lower.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 201, 0.00058515, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 201, 0.34537023, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 201, 0.54200029, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 201, 0.0981451, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 201, 0.04810765, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 201, 0.01960515, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.R\"].location[1]", 201, 0.69016731, "c_eyelid_lower.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 201, 0.00088734, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[2]", 201, 0.00016975, "c_jaw_target_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 201, 0.00206867, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[1]", 201, 0.01156745, "c_jaw_target_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_close\"].location[2]", 201, 0.00156198, "c_mouth_close_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_funnel\"].location[2]", 201, 0.00028832, "c_mouth_funnel_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_pucker\"].location[2]", 201, 0.00385052, "c_mouth_pucker_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.L\"].rotation_euler[2]", 201, 0.00071792, "c_mouth_smile.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.R\"].rotation_euler[2]", 201, 0.00051309, "c_mouth_smile.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.L\"].rotation_euler[2]", 201, 0.00024247, "c_mouth_frown.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.R\"].rotation_euler[2]", 201, 0.00033973, "c_mouth_frown.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 226, 0.1244586, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 226, 0.09313164, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 226, 0.02635259, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 226, 0.16886593, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 226, 0.09261809, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.L\"].location[1]", 226, 0.38180143, "c_eyelid_lower.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 226, 0.00565232, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 226, 0.06213954, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 226, 0.08345454, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 226, 0.03815752, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 226, 0.13662334, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 226, 0.10560638, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.R\"].location[1]", 226, 0.32952324, "c_eyelid_lower.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 226, 0.0067742, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[2]", 226, 0.0001033, "c_jaw_target_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 226, 0.00354249, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[1]", 226, 0.01170541, "c_jaw_target_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_close\"].location[2]", 226, 0.00100673, "c_mouth_close_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_funnel\"].location[2]", 226, 0.00049578, "c_mouth_funnel_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_pucker\"].location[2]", 226, 0.02363066, "c_mouth_pucker_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.L\"].rotation_euler[2]", 226, 0.00040461, "c_mouth_frown.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.R\"].rotation_euler[2]", 226, 0.0004092, "c_mouth_frown.R_ROT_Z"))
keyframe_data.extend(chunk_keyframes)
print("Prepared chunk 5: {} keyframes".format(len(chunk_keyframes)))

# Processing frames 251 to 300
chunk_keyframes = []
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 251, 0.18080167, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 251, 0.16683446, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 251, 0.05754964, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 251, 0.08200899, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 251, 0.06348666, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.L\"].location[1]", 251, 0.43853709, "c_eyelid_lower.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 251, 0.0061192, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 251, 0.10055809, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 251, 0.17921162, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 251, 0.0550588, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 251, 0.09404834, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 251, 0.05567823, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.R\"].location[1]", 251, 0.27432311, "c_eyelid_lower.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 251, 0.00675704, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[2]", 251, 0.00255898, "c_jaw_target_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 251, 0.00115247, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[1]", 251, 0.00687686, "c_jaw_target_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_close\"].location[2]", 251, 0.00014014, "c_mouth_close_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_funnel\"].location[2]", 251, 0.00398005, "c_mouth_funnel_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_pucker\"].location[2]", 251, 0.00196371, "c_mouth_pucker_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.L\"].rotation_euler[2]", 251, 0.85780871, "c_mouth_smile.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.R\"].rotation_euler[2]", 251, 0.82195848, "c_mouth_smile.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.L\"].rotation_euler[2]", 251, 0.00027563, "c_mouth_frown.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.R\"].rotation_euler[2]", 251, 0.00027627, "c_mouth_frown.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 276, 0.15975694, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 276, 0.14131601, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 276, 0.04129362, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 276, 0.10380577, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 276, 0.07997677, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.L\"].location[1]", 276, 0.51719296, "c_eyelid_lower.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 276, 0.00377332, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 276, 0.09668629, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 276, 0.13013037, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 276, 0.06625792, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 276, 0.07154803, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 276, 0.10027704, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.R\"].location[1]", 276, 0.51239181, "c_eyelid_lower.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 276, 0.00621485, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[2]", 276, 0.00032107, "c_jaw_target_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 276, 0.00013486, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 276, 0.00198992, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[1]", 276, 0.01378778, "c_jaw_target_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_close\"].location[2]", 276, 0.00076196, "c_mouth_close_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_funnel\"].location[2]", 276, 0.00080434, "c_mouth_funnel_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_pucker\"].location[2]", 276, 0.00886861, "c_mouth_pucker_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.L\"].rotation_euler[2]", 276, 0.00022267, "c_mouth_smile.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.R\"].rotation_euler[2]", 276, 0.00011077, "c_mouth_smile.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.L\"].rotation_euler[2]", 276, 0.00022309, "c_mouth_frown.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.R\"].rotation_euler[2]", 276, 0.0004112, "c_mouth_frown.R_ROT_Z"))
keyframe_data.extend(chunk_keyframes)
print("Prepared chunk 6: {} keyframes".format(len(chunk_keyframes)))

# Processing frames 301 to 350
chunk_keyframes = []
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 301, 0.51184815, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 301, 0.5012449, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 301, 0.10035905, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 301, 0.04505252, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 301, 0.012429, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.L\"].location[1]", 301, 0.47173592, "c_eyelid_lower.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 301, 0.00078146, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 301, 0.30147409, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 301, 0.49616969, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 301, 0.05035618, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 301, 0.09556199, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 301, 0.01831984, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.R\"].location[1]", 301, 0.50780296, "c_eyelid_lower.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 301, 0.00097483, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[2]", 301, 0.00012347, "c_jaw_target_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 301, 0.00268369, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[1]", 301, 0.00952706, "c_jaw_target_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_close\"].location[2]", 301, 0.00101591, "c_mouth_close_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_funnel\"].location[2]", 301, 0.00024809, "c_mouth_funnel_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_pucker\"].location[2]", 301, 0.00325867, "c_mouth_pucker_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.L\"].rotation_euler[2]", 301, 0.00046143, "c_mouth_smile.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.R\"].rotation_euler[2]", 301, 0.00028198, "c_mouth_smile.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.L\"].rotation_euler[2]", 301, 0.00044691, "c_mouth_frown.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.R\"].rotation_euler[2]", 301, 0.0004607, "c_mouth_frown.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 326, 0.19713925, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 326, 0.1838827, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 326, 0.0490746, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 326, 0.09037285, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 326, 0.04859056, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.L\"].location[1]", 326, 0.3970699, "c_eyelid_lower.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 326, 0.00384722, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 326, 0.12431663, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 326, 0.19987762, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 326, 0.06368655, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 326, 0.07579326, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 326, 0.04899799, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.R\"].location[1]", 326, 0.34449461, "c_eyelid_lower.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 326, 0.00438161, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[2]", 326, 0.00022401, "c_jaw_target_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 326, 0.00075848, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[1]", 326, 0.00123138, "c_jaw_target_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_funnel\"].location[2]", 326, 0.00065857, "c_mouth_funnel_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_pucker\"].location[2]", 326, 0.00491294, "c_mouth_pucker_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.L\"].rotation_euler[2]", 326, 0.65877724, "c_mouth_smile.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.R\"].rotation_euler[2]", 326, 0.52065992, "c_mouth_smile.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.L\"].rotation_euler[2]", 326, 0.00016784, "c_mouth_frown.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.R\"].rotation_euler[2]", 326, 0.0001681, "c_mouth_frown.R_ROT_Z"))
keyframe_data.extend(chunk_keyframes)
print("Prepared chunk 7: {} keyframes".format(len(chunk_keyframes)))

# Processing frames 351 to 400
chunk_keyframes = []
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 351, 0.00177532, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 351, 0.17496002, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 351, 0.12481239, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 351, 0.03396432, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 351, 0.0698209, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.L\"].location[1]", 351, 0.01335064, "c_eyelid_lower.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 351, 0.28298631, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 351, 0.00080573, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 351, 0.16563936, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 351, 0.03718942, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 351, 0.12183523, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 351, 0.07902073, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.R\"].location[1]", 351, 0.01006384, "c_eyelid_lower.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 351, 0.38704881, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[2]", 351, 0.00058754, "c_jaw_target_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 351, 0.00121105, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 351, 0.07931564, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[1]", 351, 0.6082716, "c_jaw_target_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_close\"].location[2]", 351, 0.00078785, "c_mouth_close_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_funnel\"].location[2]", 351, 0.01598824, "c_mouth_funnel_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_pucker\"].location[2]", 351, 0.03171221, "c_mouth_pucker_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.L\"].rotation_euler[2]", 351, 0.00080798, "c_mouth_smile.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.R\"].rotation_euler[2]", 351, 0.00067487, "c_mouth_smile.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.L\"].rotation_euler[2]", 351, 0.00135401, "c_mouth_frown.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.R\"].rotation_euler[2]", 351, 0.00155695, "c_mouth_frown.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 376, 0.00123199, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 376, 0.25566944, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 376, 0.1602224, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 376, 0.02368965, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 376, 0.04121862, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.L\"].location[1]", 376, 0.00509732, "c_eyelid_lower.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 376, 0.32811549, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 376, 0.00046515, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 376, 0.21503995, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 376, 0.02531801, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 376, 0.16007173, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 376, 0.05449427, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.R\"].location[1]", 376, 0.00419541, "c_eyelid_lower.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 376, 0.52911347, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[2]", 376, 0.00063636, "c_jaw_target_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 376, 0.00170136, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 376, 0.05742287, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[1]", 376, 0.43563658, "c_jaw_target_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_close\"].location[2]", 376, 0.00062973, "c_mouth_close_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_funnel\"].location[2]", 376, 0.0058167, "c_mouth_funnel_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_pucker\"].location[2]", 376, 0.01882905, "c_mouth_pucker_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.L\"].rotation_euler[2]", 376, 0.0005582, "c_mouth_smile.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.R\"].rotation_euler[2]", 376, 0.00071525, "c_mouth_smile.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.L\"].rotation_euler[2]", 376, 0.01741, "c_mouth_frown.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.R\"].rotation_euler[2]", 376, 0.02630895, "c_mouth_frown.R_ROT_Z"))
keyframe_data.extend(chunk_keyframes)
print("Prepared chunk 8: {} keyframes".format(len(chunk_keyframes)))

# Processing frames 401 to 411
chunk_keyframes = []
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 401, 0.00117942, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 401, 0.34207657, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 401, 0.09851881, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 401, 0.0495478, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 401, 0.03942013, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.L\"].location[1]", 401, 0.00792379, "c_eyelid_lower.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 401, 0.41300061, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 401, 0.00042216, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 401, 0.32154897, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 401, 0.05971099, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 401, 0.08133075, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 401, 0.04225032, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.R\"].location[1]", 401, 0.00318764, "c_eyelid_lower.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 401, 0.62243021, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[2]", 401, 0.00110267, "c_jaw_target_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 401, 0.00204869, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 401, 0.06260297, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[1]", 401, 0.61224103, "c_jaw_target_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_close\"].location[2]", 401, 0.00083077, "c_mouth_close_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_funnel\"].location[2]", 401, 0.00822406, "c_mouth_funnel_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_pucker\"].location[2]", 401, 0.01338606, "c_mouth_pucker_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.L\"].rotation_euler[2]", 401, 0.00185344, "c_mouth_smile.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.R\"].rotation_euler[2]", 401, 0.00261866, "c_mouth_smile.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.L\"].rotation_euler[2]", 401, 0.01636172, "c_mouth_frown.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.R\"].rotation_euler[2]", 401, 0.02953139, "c_mouth_frown.R_ROT_Z"))
keyframe_data.extend(chunk_keyframes)
print("Prepared chunk 9: {} keyframes".format(len(chunk_keyframes)))


# Insert all keyframes in batches
print(f"Total keyframes prepared: {len(keyframe_data)}")
if keyframe_data:
    batch_keyframe_insert(keyframe_data)
else:
    print("No keyframes to insert")


# Finalize
end_time = time.time()
print(f"Animation import completed in {end_time - start_time:.2f} seconds")

# Update scene
bpy.context.scene.frame_end = max([kf[2] for kf in keyframe_data]) if keyframe_data else 1
print(f"Scene frame range updated to: 1 - {bpy.context.scene.frame_end}")

print("Mocap animation import finished successfully!")
