import bpy
import bmesh
import mathutils
from mathutils import Vector
import time

# Animation Import Script - Optimized for Performance
# Generated by BlenderScriptGenerator
print("Starting mocap animation import...")

def safe_keyframe_insert(obj, data_path, frame, value, group_name=""):
    """Safely insert a keyframe with error handling."""
    try:
        if hasattr(obj, data_path.split('.')[0]):
            obj.keyframe_insert(data_path=data_path, frame=frame, group=group_name)
            return True
    except Exception as e:
        print(f"Warning: Failed to insert keyframe for {data_path} at frame {frame}: {e}")
        return False
    return False

def batch_keyframe_insert(keyframe_data, progress_callback=None):
    """
    Insert keyframes in batches for better performance.
    
    Args:
        keyframe_data: List of (object, data_path, frame, value, group) tuples
        progress_callback: Optional callback for progress updates
    """
    total_keyframes = len(keyframe_data)
    print(f"Inserting {total_keyframes} keyframes in batches...")
    
    # Group keyframes by object and data path for efficiency
    grouped_keyframes = {}
    for obj_name, data_path, frame, value, group in keyframe_data:
        key = (obj_name, data_path)
        if key not in grouped_keyframes:
            grouped_keyframes[key] = []
        grouped_keyframes[key].append((frame, value, group))
    
    success_count = 0
    total_groups = len(grouped_keyframes)
    
    for i, ((obj_name, data_path), keyframes) in enumerate(grouped_keyframes.items()):
        try:
            # Get the object
            obj = bpy.data.objects.get(obj_name)
            if not obj:
                print(f"Warning: Object '{obj_name}' not found")
                continue
            
            # Select and make active
            bpy.context.view_layer.objects.active = obj
            obj.select_set(True)
            
            # Insert keyframes for this object/data_path combination
            for frame, value, group in keyframes:
                # Set the value
                try:
                    if '.' in data_path:
                        # Handle nested attributes (e.g., pose.bones["name"].location)
                        parts = data_path.split('.')
                        current_obj = obj
                        for part in parts[:-1]:
                            if '[' in part and ']' in part:
                                # Handle array access like bones["name"]
                                attr_name = part.split('[')[0]
                                index_part = part.split('[')[1].split(']')[0]
                                index = index_part.replace('"', '').replace("'", '')
                                current_obj = getattr(current_obj, attr_name)[index]
                            else:
                                current_obj = getattr(current_obj, part)
                        
                        # Set the final value
                        final_attr = parts[-1]
                        if hasattr(current_obj, final_attr):
                            if isinstance(getattr(current_obj, final_attr), (int, float)):
                                setattr(current_obj, final_attr, float(value))
                            else:
                                # Handle vector/array types
                                current_value = getattr(current_obj, final_attr)
                                if hasattr(current_value, '__setitem__'):
                                    # This is likely a vector or array
                                    if len(current_value) > 0:
                                        current_value[0] = float(value)  # Assuming single axis for now
                    else:
                        # Simple attribute
                        if hasattr(obj, data_path):
                            setattr(obj, data_path, float(value))
                    
                    # Insert keyframe
                    if safe_keyframe_insert(obj, data_path, frame, value, group):
                        success_count += 1
                        
                except Exception as e:
                    print(f"Error setting value for {obj_name}.{data_path} at frame {frame}: {e}")
                    continue
            
            # Update progress
            if progress_callback:
                progress = (i + 1) / total_groups * 100
                progress_callback(progress, f"Processing {obj_name}.{data_path}")
            elif i % 10 == 0:  # Print progress every 10 groups
                progress = (i + 1) / total_groups * 100
                print(f"Progress: {progress:.1f}% ({i+1}/{total_groups} bone mappings)")
                
        except Exception as e:
            print(f"Error processing {obj_name}.{data_path}: {e}")
            continue
    
    print(f"Successfully inserted {success_count} keyframes")
    return success_count

# Start timing
start_time = time.time()

# Prepare keyframe data
keyframe_data = []

# Processing frames 1 to 50
chunk_keyframes = []
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 1, 0.1173306, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 1, 0.18357788, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 1, 0.20758107, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 1, 0.02790979, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 1, 0.04860202, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.L\"].location[1]", 1, 0.34338242, "c_eyelid_lower.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 1, 0.00521958, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 1, 0.06477024, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 1, 0.16739362, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 1, 0.01164191, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 1, 0.22884054, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 1, 0.05752239, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.R\"].location[1]", 1, 0.33392572, "c_eyelid_lower.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 1, 0.00784608, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[2]", 1, 0.0001275, "c_jaw_target_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 1, 0.00246498, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[1]", 1, 0.01473731, "c_jaw_target_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_close\"].location[2]", 1, 0.00087887, "c_mouth_close_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_funnel\"].location[2]", 1, 0.00046822, "c_mouth_funnel_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_pucker\"].location[2]", 1, 0.00395376, "c_mouth_pucker_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.L\"].rotation_euler[2]", 1, 0.00036647, "c_mouth_smile.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.R\"].rotation_euler[2]", 1, 0.0002458, "c_mouth_smile.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.L\"].rotation_euler[2]", 1, 0.0003857, "c_mouth_frown.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.R\"].rotation_euler[2]", 1, 0.00051114, "c_mouth_frown.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 31, 0.13777575, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 31, 0.1870309, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 31, 0.06554409, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 31, 0.0734017, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 31, 0.05295279, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.L\"].location[1]", 31, 0.32804766, "c_eyelid_lower.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 31, 0.00531043, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 31, 0.05713131, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 31, 0.1698059, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 31, 0.04600889, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 31, 0.09792089, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 31, 0.06397095, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.R\"].location[1]", 31, 0.32375759, "c_eyelid_lower.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 31, 0.00986272, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 31, 0.00274437, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[1]", 31, 0.01134806, "c_jaw_target_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_close\"].location[2]", 31, 0.00088652, "c_mouth_close_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_funnel\"].location[2]", 31, 0.0004115, "c_mouth_funnel_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_pucker\"].location[2]", 31, 0.01267698, "c_mouth_pucker_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.L\"].rotation_euler[2]", 31, 0.00011163, "c_mouth_smile.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.L\"].rotation_euler[2]", 31, 0.00032968, "c_mouth_frown.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.R\"].rotation_euler[2]", 31, 0.00045033, "c_mouth_frown.R_ROT_Z"))
keyframe_data.extend(chunk_keyframes)
print("Prepared chunk 1: {} keyframes".format(len(chunk_keyframes)))

# Processing frames 51 to 100
chunk_keyframes = []
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 51, 0.13341114, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 51, 0.15671057, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 51, 0.03250477, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 51, 0.13274702, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 51, 0.05773252, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.L\"].location[1]", 51, 0.32702023, "c_eyelid_lower.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 51, 0.00597722, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 51, 0.0577823, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 51, 0.1491368, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 51, 0.05063425, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 51, 0.0966953, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 51, 0.06398761, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.R\"].location[1]", 51, 0.26945916, "c_eyelid_lower.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 51, 0.00818226, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[2]", 51, 0.00014532, "c_jaw_target_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 51, 0.00207727, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[1]", 51, 0.01080953, "c_jaw_target_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_close\"].location[2]", 51, 0.00086371, "c_mouth_close_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_funnel\"].location[2]", 51, 0.00034447, "c_mouth_funnel_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_pucker\"].location[2]", 51, 0.00457881, "c_mouth_pucker_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.L\"].rotation_euler[2]", 51, 0.00029666, "c_mouth_smile.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.R\"].rotation_euler[2]", 51, 0.00016808, "c_mouth_smile.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.L\"].rotation_euler[2]", 51, 0.00094736, "c_mouth_frown.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.R\"].rotation_euler[2]", 51, 0.0014366, "c_mouth_frown.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 81, 0.097507, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 81, 0.0866226, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 81, 0.02979092, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 81, 0.15254539, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 81, 0.09450299, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.L\"].location[1]", 81, 0.32510513, "c_eyelid_lower.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 81, 0.00741295, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 81, 0.03779079, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 81, 0.07839304, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 81, 0.03407315, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 81, 0.14297515, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 81, 0.11047654, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.R\"].location[1]", 81, 0.23894104, "c_eyelid_lower.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 81, 0.01178907, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 81, 0.00331797, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[1]", 81, 0.0124826, "c_jaw_target_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_close\"].location[2]", 81, 0.00082982, "c_mouth_close_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_funnel\"].location[2]", 81, 0.00046398, "c_mouth_funnel_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_pucker\"].location[2]", 81, 0.01667231, "c_mouth_pucker_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.L\"].rotation_euler[2]", 81, 0.00113903, "c_mouth_frown.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.R\"].rotation_euler[2]", 81, 0.00133525, "c_mouth_frown.R_ROT_Z"))
keyframe_data.extend(chunk_keyframes)
print("Prepared chunk 2: {} keyframes".format(len(chunk_keyframes)))

# Processing frames 101 to 150
chunk_keyframes = []
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 101, 0.09601054, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 101, 0.0984168, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 101, 0.15371393, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 101, 0.03591713, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 101, 0.09609891, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.L\"].location[1]", 101, 0.33393586, "c_eyelid_lower.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 101, 0.00804043, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 101, 0.03642641, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 101, 0.09208748, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 101, 0.01878528, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 101, 0.17539376, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 101, 0.11214609, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.R\"].location[1]", 101, 0.2107881, "c_eyelid_lower.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 101, 0.01257551, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 101, 0.00227173, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[1]", 101, 0.009757, "c_jaw_target_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_close\"].location[2]", 101, 0.00079893, "c_mouth_close_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_funnel\"].location[2]", 101, 0.00038266, "c_mouth_funnel_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_pucker\"].location[2]", 101, 0.00904825, "c_mouth_pucker_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.L\"].rotation_euler[2]", 101, 0.00013454, "c_mouth_smile.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.L\"].rotation_euler[2]", 101, 0.00059985, "c_mouth_frown.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.R\"].rotation_euler[2]", 101, 0.00112797, "c_mouth_frown.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 131, 0.09433517, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 131, 0.1386576, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 131, 0.34126467, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 131, 0.01681793, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 131, 0.06312822, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.L\"].location[1]", 131, 0.3014684, "c_eyelid_lower.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 131, 0.00709932, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 131, 0.03108184, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 131, 0.12026388, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 131, 0.0064814, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 131, 0.29565161, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 131, 0.07901762, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.R\"].location[1]", 131, 0.20688231, "c_eyelid_lower.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 131, 0.01449228, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[2]", 131, 0.00010466, "c_jaw_target_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 131, 0.00326843, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[1]", 131, 0.01371355, "c_jaw_target_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_close\"].location[2]", 131, 0.0010285, "c_mouth_close_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_funnel\"].location[2]", 131, 0.00067218, "c_mouth_funnel_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_pucker\"].location[2]", 131, 0.00921388, "c_mouth_pucker_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.L\"].rotation_euler[2]", 131, 0.00018185, "c_mouth_smile.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.R\"].rotation_euler[2]", 131, 0.00014304, "c_mouth_smile.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.L\"].rotation_euler[2]", 131, 0.00046251, "c_mouth_frown.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.R\"].rotation_euler[2]", 131, 0.00067119, "c_mouth_frown.R_ROT_Z"))
keyframe_data.extend(chunk_keyframes)
print("Prepared chunk 3: {} keyframes".format(len(chunk_keyframes)))

# Processing frames 151 to 200
chunk_keyframes = []
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 151, 0.09512791, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 151, 0.09864005, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 151, 0.0770466, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 151, 0.06401817, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 151, 0.08660775, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.L\"].location[1]", 151, 0.30032521, "c_eyelid_lower.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 151, 0.00803785, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 151, 0.04630291, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 151, 0.09888109, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 151, 0.03836761, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 151, 0.11578699, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 151, 0.09500144, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.R\"].location[1]", 151, 0.20625803, "c_eyelid_lower.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 151, 0.00948152, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[2]", 151, 0.00030429, "c_jaw_target_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 151, 0.00127983, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[1]", 151, 0.00269457, "c_jaw_target_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_close\"].location[2]", 151, 0.00028767, "c_mouth_close_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_funnel\"].location[2]", 151, 0.00030182, "c_mouth_funnel_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_pucker\"].location[2]", 151, 0.00056283, "c_mouth_pucker_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.L\"].rotation_euler[2]", 151, 0.02633386, "c_mouth_smile.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.R\"].rotation_euler[2]", 151, 0.01750213, "c_mouth_smile.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.L\"].rotation_euler[2]", 151, 0.00031639, "c_mouth_frown.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.R\"].rotation_euler[2]", 151, 0.00040485, "c_mouth_frown.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 181, 0.14209729, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 181, 0.21723486, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 181, 0.05472942, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 181, 0.0751454, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 181, 0.03901661, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.L\"].location[1]", 181, 0.38700339, "c_eyelid_lower.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 181, 0.00691133, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 181, 0.09024899, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 181, 0.22962955, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 181, 0.04353113, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 181, 0.09936663, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 181, 0.03477468, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.R\"].location[1]", 181, 0.23863181, "c_eyelid_lower.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 181, 0.00550544, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[2]", 181, 0.00017526, "c_jaw_target_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 181, 0.00045668, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[1]", 181, 0.00086858, "c_jaw_target_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_funnel\"].location[2]", 181, 0.00019126, "c_mouth_funnel_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_pucker\"].location[2]", 181, 0.00124828, "c_mouth_pucker_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.L\"].rotation_euler[2]", 181, 0.6656388, "c_mouth_smile.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.R\"].rotation_euler[2]", 181, 0.5863843, "c_mouth_smile.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.L\"].rotation_euler[2]", 181, 0.00136028, "c_mouth_frown.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.R\"].rotation_euler[2]", 181, 0.00138547, "c_mouth_frown.R_ROT_Z"))
keyframe_data.extend(chunk_keyframes)
print("Prepared chunk 4: {} keyframes".format(len(chunk_keyframes)))

# Processing frames 201 to 250
chunk_keyframes = []
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 201, 0.5862301, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 201, 0.54950207, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 201, 0.07456706, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 201, 0.07714885, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 201, 0.01046647, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.L\"].location[1]", 201, 0.56207073, "c_eyelid_lower.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 201, 0.00058515, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 201, 0.34537023, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 201, 0.54200029, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 201, 0.0981451, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 201, 0.04810765, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 201, 0.01960515, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.R\"].location[1]", 201, 0.69016731, "c_eyelid_lower.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 201, 0.00088734, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[2]", 201, 0.00016975, "c_jaw_target_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 201, 0.00206867, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[1]", 201, 0.01156745, "c_jaw_target_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_close\"].location[2]", 201, 0.00156198, "c_mouth_close_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_funnel\"].location[2]", 201, 0.00028832, "c_mouth_funnel_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_pucker\"].location[2]", 201, 0.00385052, "c_mouth_pucker_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.L\"].rotation_euler[2]", 201, 0.00071792, "c_mouth_smile.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.R\"].rotation_euler[2]", 201, 0.00051309, "c_mouth_smile.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.L\"].rotation_euler[2]", 201, 0.00024247, "c_mouth_frown.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.R\"].rotation_euler[2]", 201, 0.00033973, "c_mouth_frown.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 231, 0.10909463, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 231, 0.09348076, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 231, 0.02850074, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 231, 0.15724595, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 231, 0.09082321, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.L\"].location[1]", 231, 0.32770547, "c_eyelid_lower.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 231, 0.0067679, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 231, 0.05458177, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 231, 0.08714964, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 231, 0.04135027, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 231, 0.1250062, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 231, 0.10111854, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.R\"].location[1]", 231, 0.28466338, "c_eyelid_lower.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 231, 0.00760975, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 231, 0.00308285, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[1]", 231, 0.01203086, "c_jaw_target_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_close\"].location[2]", 231, 0.00122886, "c_mouth_close_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_funnel\"].location[2]", 231, 0.00060168, "c_mouth_funnel_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_pucker\"].location[2]", 231, 0.02105311, "c_mouth_pucker_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.L\"].rotation_euler[2]", 231, 0.00012516, "c_mouth_smile.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.L\"].rotation_euler[2]", 231, 0.00017097, "c_mouth_frown.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.R\"].rotation_euler[2]", 231, 0.00019673, "c_mouth_frown.R_ROT_Z"))
keyframe_data.extend(chunk_keyframes)
print("Prepared chunk 5: {} keyframes".format(len(chunk_keyframes)))

# Processing frames 251 to 300
chunk_keyframes = []
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 251, 0.18080167, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 251, 0.16683446, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 251, 0.05754964, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 251, 0.08200899, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 251, 0.06348666, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.L\"].location[1]", 251, 0.43853709, "c_eyelid_lower.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 251, 0.0061192, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 251, 0.10055809, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 251, 0.17921162, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 251, 0.0550588, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 251, 0.09404834, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 251, 0.05567823, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.R\"].location[1]", 251, 0.27432311, "c_eyelid_lower.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 251, 0.00675704, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[2]", 251, 0.00255898, "c_jaw_target_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 251, 0.00115247, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[1]", 251, 0.00687686, "c_jaw_target_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_close\"].location[2]", 251, 0.00014014, "c_mouth_close_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_funnel\"].location[2]", 251, 0.00398005, "c_mouth_funnel_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_pucker\"].location[2]", 251, 0.00196371, "c_mouth_pucker_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.L\"].rotation_euler[2]", 251, 0.85780871, "c_mouth_smile.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.R\"].rotation_euler[2]", 251, 0.82195848, "c_mouth_smile.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.L\"].rotation_euler[2]", 251, 0.00027563, "c_mouth_frown.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.R\"].rotation_euler[2]", 251, 0.00027627, "c_mouth_frown.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 281, 0.13783388, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 281, 0.11725514, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 281, 0.02906857, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 281, 0.13195945, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 281, 0.09021308, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.L\"].location[1]", 281, 0.47863454, "c_eyelid_lower.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 281, 0.00444878, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 281, 0.0752684, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 281, 0.11162812, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 281, 0.08191769, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 281, 0.06260479, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 281, 0.1108762, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.R\"].location[1]", 281, 0.42259249, "c_eyelid_lower.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 281, 0.00822943, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[2]", 281, 0.00026408, "c_jaw_target_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 281, 0.0001029, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 281, 0.00280277, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[1]", 281, 0.0137496, "c_jaw_target_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_close\"].location[2]", 281, 0.00099323, "c_mouth_close_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_funnel\"].location[2]", 281, 0.00063791, "c_mouth_funnel_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_pucker\"].location[2]", 281, 0.00828982, "c_mouth_pucker_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.L\"].rotation_euler[2]", 281, 0.00026452, "c_mouth_smile.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.R\"].rotation_euler[2]", 281, 0.00012923, "c_mouth_smile.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.L\"].rotation_euler[2]", 281, 0.00023884, "c_mouth_frown.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.R\"].rotation_euler[2]", 281, 0.0003734, "c_mouth_frown.R_ROT_Z"))
keyframe_data.extend(chunk_keyframes)
print("Prepared chunk 6: {} keyframes".format(len(chunk_keyframes)))

# Processing frames 301 to 350
chunk_keyframes = []
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 301, 0.51184815, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 301, 0.5012449, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 301, 0.10035905, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 301, 0.04505252, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 301, 0.012429, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.L\"].location[1]", 301, 0.47173592, "c_eyelid_lower.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 301, 0.00078146, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 301, 0.30147409, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 301, 0.49616969, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 301, 0.05035618, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 301, 0.09556199, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 301, 0.01831984, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.R\"].location[1]", 301, 0.50780296, "c_eyelid_lower.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 301, 0.00097483, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[2]", 301, 0.00012347, "c_jaw_target_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 301, 0.00268369, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[1]", 301, 0.00952706, "c_jaw_target_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_close\"].location[2]", 301, 0.00101591, "c_mouth_close_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_funnel\"].location[2]", 301, 0.00024809, "c_mouth_funnel_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_pucker\"].location[2]", 301, 0.00325867, "c_mouth_pucker_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.L\"].rotation_euler[2]", 301, 0.00046143, "c_mouth_smile.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.R\"].rotation_euler[2]", 301, 0.00028198, "c_mouth_smile.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.L\"].rotation_euler[2]", 301, 0.00044691, "c_mouth_frown.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.R\"].rotation_euler[2]", 301, 0.0004607, "c_mouth_frown.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 331, 0.11048285, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 331, 0.09671355, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 331, 0.09640234, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 331, 0.04715376, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 331, 0.10478198, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.L\"].location[1]", 331, 0.30220032, "c_eyelid_lower.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 331, 0.00802916, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 331, 0.03286864, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 331, 0.08720941, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 331, 0.03653226, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 331, 0.11465004, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 331, 0.10909428, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.R\"].location[1]", 331, 0.18192025, "c_eyelid_lower.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 331, 0.01861405, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[2]", 331, 0.00267043, "c_jaw_target_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 331, 0.00025163, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 331, 0.00136287, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[1]", 331, 0.03441947, "c_jaw_target_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_close\"].location[2]", 331, 0.00053102, "c_mouth_close_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_funnel\"].location[2]", 331, 0.01323652, "c_mouth_funnel_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_pucker\"].location[2]", 331, 0.00526997, "c_mouth_pucker_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.L\"].rotation_euler[2]", 331, 0.74289542, "c_mouth_smile.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.R\"].rotation_euler[2]", 331, 0.6753996, "c_mouth_smile.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.L\"].rotation_euler[2]", 331, 0.00023601, "c_mouth_frown.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.R\"].rotation_euler[2]", 331, 0.00027101, "c_mouth_frown.R_ROT_Z"))
keyframe_data.extend(chunk_keyframes)
print("Prepared chunk 7: {} keyframes".format(len(chunk_keyframes)))

# Processing frames 351 to 400
chunk_keyframes = []
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 351, 0.00177532, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 351, 0.17496002, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 351, 0.12481239, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 351, 0.03396432, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 351, 0.0698209, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.L\"].location[1]", 351, 0.01335064, "c_eyelid_lower.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 351, 0.28298631, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 351, 0.00080573, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 351, 0.16563936, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 351, 0.03718942, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 351, 0.12183523, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 351, 0.07902073, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.R\"].location[1]", 351, 0.01006384, "c_eyelid_lower.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 351, 0.38704881, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[2]", 351, 0.00058754, "c_jaw_target_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 351, 0.00121105, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 351, 0.07931564, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[1]", 351, 0.6082716, "c_jaw_target_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_close\"].location[2]", 351, 0.00078785, "c_mouth_close_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_funnel\"].location[2]", 351, 0.01598824, "c_mouth_funnel_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_pucker\"].location[2]", 351, 0.03171221, "c_mouth_pucker_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.L\"].rotation_euler[2]", 351, 0.00080798, "c_mouth_smile.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.R\"].rotation_euler[2]", 351, 0.00067487, "c_mouth_smile.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.L\"].rotation_euler[2]", 351, 0.00135401, "c_mouth_frown.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.R\"].rotation_euler[2]", 351, 0.00155695, "c_mouth_frown.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 381, 0.00146151, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 381, 0.22881304, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 381, 0.09045787, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 381, 0.04395604, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 381, 0.03731599, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.L\"].location[1]", 381, 0.00760676, "c_eyelid_lower.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 381, 0.25797147, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 381, 0.00053792, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 381, 0.22849746, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 381, 0.03501023, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 381, 0.10577422, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 381, 0.04106694, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.R\"].location[1]", 381, 0.0034922, "c_eyelid_lower.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 381, 0.42457503, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[2]", 381, 0.00013135, "c_jaw_target_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 381, 0.00115527, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 381, 0.01295029, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[1]", 381, 0.25610793, "c_jaw_target_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_close\"].location[2]", 381, 0.00084411, "c_mouth_close_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_funnel\"].location[2]", 381, 0.00259947, "c_mouth_funnel_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_pucker\"].location[2]", 381, 0.022501, "c_mouth_pucker_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.L\"].rotation_euler[2]", 381, 0.00740331, "c_mouth_frown.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.R\"].rotation_euler[2]", 381, 0.00871099, "c_mouth_frown.R_ROT_Z"))
keyframe_data.extend(chunk_keyframes)
print("Prepared chunk 8: {} keyframes".format(len(chunk_keyframes)))

# Processing frames 401 to 411
chunk_keyframes = []
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 401, 0.00117942, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 401, 0.34207657, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 401, 0.09851881, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[2]", 401, 0.0495478, "c_lookat_mch.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.L\"].rotation_euler[0]", 401, 0.03942013, "c_lookat_mch.L_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.L\"].location[1]", 401, 0.00792379, "c_eyelid_lower.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.L\"].location[1]", 401, 0.41300061, "c_eyelid_upper.L_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 401, 0.00042216, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 401, 0.32154897, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 401, 0.05971099, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[2]", 401, 0.08133075, "c_lookat_mch.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_lookat_mch.R\"].rotation_euler[0]", 401, 0.04225032, "c_lookat_mch.R_ROT_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_lower.R\"].location[1]", 401, 0.00318764, "c_eyelid_lower.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_eyelid_upper.R\"].location[1]", 401, 0.62243021, "c_eyelid_upper.R_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[2]", 401, 0.00110267, "c_jaw_target_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 401, 0.00204869, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[0]", 401, 0.06260297, "c_jaw_target_LOC_X"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_jaw_target\"].location[1]", 401, 0.61224103, "c_jaw_target_LOC_Y"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_close\"].location[2]", 401, 0.00083077, "c_mouth_close_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_funnel\"].location[2]", 401, 0.00822406, "c_mouth_funnel_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_pucker\"].location[2]", 401, 0.01338606, "c_mouth_pucker_LOC_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.L\"].rotation_euler[2]", 401, 0.00185344, "c_mouth_smile.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_smile.R\"].rotation_euler[2]", 401, 0.00261866, "c_mouth_smile.R_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.L\"].rotation_euler[2]", 401, 0.01636172, "c_mouth_frown.L_ROT_Z"))
chunk_keyframes.append(("FaceitControlRig", "pose.bones[\"c_mouth_frown.R\"].rotation_euler[2]", 401, 0.02953139, "c_mouth_frown.R_ROT_Z"))
keyframe_data.extend(chunk_keyframes)
print("Prepared chunk 9: {} keyframes".format(len(chunk_keyframes)))


# Insert all keyframes in batches
print(f"Total keyframes prepared: {len(keyframe_data)}")
if keyframe_data:
    batch_keyframe_insert(keyframe_data)
else:
    print("No keyframes to insert")


# Finalize
end_time = time.time()
print(f"Animation import completed in {end_time - start_time:.2f} seconds")

# Update scene
bpy.context.scene.frame_end = max([kf[2] for kf in keyframe_data]) if keyframe_data else 1
print(f"Scene frame range updated to: 1 - {bpy.context.scene.frame_end}")

print("Mocap animation import finished successfully!")
